version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
    - bodyclose
    - dupl
    - copyloopvar
    - forcetypeassert
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wrapcheck
  settings:
    gocyclo:
      min-complexity: 16
    misspell:
      locale: US
    funlen:
      lines: 100
      statements: 60
    wrapcheck:
      ignore-sigs:
        - .WrapAndTrace
        - .Errorf
        - .Wrap
        - .New

run:
  build-tags:
    - codeanalysis

formatters:
  enable:
    - gofumpt
