before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      # - windows
    goarch:
      - amd64
      - arm64
    binary: brev
    ldflags:
      - -X github.com/brevdev/brev-cli/pkg/cmd/version.Version={{.Tag}}

brews:
  - name: brev
    folder: Formula
    # GitHub/GitLab repository to push the formula to
    repository:
      owner: brevdev
      name: homebrew-brev
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://docs.nvidia.com/brev/latest/"
    description: "CLI tool for managing workspaces provided by brev.nvidia.com"
    install: |
      bin.install "brev"
      generate_completions_from_executable("#{bin}/brev", "completion")
    test: |
      system "#{bin}/brev" "--version"

archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github:
  prerelease: auto
# dockers:
#   - image_templates:
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:latest"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
