before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      # - windows
    goarch:
      - amd64
      - arm64
    binary: brev
    ldflags:
      - -X github.com/brevdev/brev-cli/pkg/cmd/version.Version={{.Tag}}
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github:
  prerelease: auto
# dockers:
#   - image_templates:
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:latest"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
