# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrevCli < Formula
  desc ""
  homepage "https://docs.brev.dev"
  version "0.6.10"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.10/brev-cli_0.6.10_darwin_amd64.tar.gz"
      sha256 "e87399d76aebeaebf8d3d00a3efd38bccedfb7c49b35c90b4d339bf67bbbaa7f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.10/brev-cli_0.6.10_darwin_arm64.tar.gz"
      sha256 "6014aef67b927187e3320bfeccac1c450ed852bf99aea2cb12ae454d3bfb9e3b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.10/brev-cli_0.6.10_linux_amd64.tar.gz"
      sha256 "07f71663cbaae1d7cb5f4efb8862885ebfc42f74b7350d2add30b307684bac58"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.10/brev-cli_0.6.10_linux_arm64.tar.gz"
      sha256 "fe3666fba5fffed80d43f9aae47105b4481c2d8219586387839f80c61cf2e2a3"
    end
  end

  def install
    bin.install "brev"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>dev.brev</string>
    <key>ProgramArguments</key>
    <array>
      <string>brev</string>
      <string>run-tasks</string>
    </array>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>

  EOS
  end
end
