# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrevCli < Formula
  desc ""
  homepage ""
  version "0.6.7"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.7/brev-cli_0.6.7_darwin_amd64.tar.gz"
      sha256 "62ce8e46b96c09d661be01866ccb5b1a45234d14297f9e63316fd1f1ce4d3299"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.7/brev-cli_0.6.7_linux_amd64.tar.gz"
      sha256 "cc94a32dc702fe2240419def39e54264c4f93c09935fef36addd489a263eb983"
    end
  end

  def install
    bin.install "brev-cli"
  end
end
