package spark

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	breverrors "github.com/brevdev/brev-cli/pkg/errors"
)

// ConfigLocator resolves the path to the Sync-managed ssh_config.
type ConfigLocator interface {
	ConfigPath() (string, error)
}

// SyncSSHConfigLocator resolves the ssh_config generated by NVIDIA Sync.
type SyncSSHConfigLocator struct {
	homeDir func() (string, error)
	goos    string
}

func NewSyncSSHConfigLocator() SyncSSHConfigLocator {
	return SyncSSHConfigLocator{
		homeDir: os.UserHomeDir,
		goos:    runtime.GOOS,
	}
}

func NewSyncSSHConfigLocatorWithHome(home func() (string, error), goos string) SyncSSHConfigLocator {
	return SyncSSHConfigLocator{
		homeDir: home,
		goos:    goos,
	}
}

// ConfigPath returns the platform-appropriate path to the Sync ssh_config file.
func (l SyncSSHConfigLocator) ConfigPath() (string, error) {
	home, err := l.homeDir()
	if err != nil {
		return "", breverrors.WrapAndTrace(err)
	}

	var parts []string
	switch l.goos {
	case "darwin":
		parts = []string{home, "Library", "Application Support", "NVIDIA", "Sync", "config", "ssh_config"}
	case "linux":
		parts = []string{home, ".config", "NVIDIA", "Sync", "config", "ssh_config"}
	case "windows":
		parts = []string{home, "AppData", "Local", "NVIDIA Corporation", "Sync", "config", "ssh_config"}
	default:
		return "", breverrors.WrapAndTrace(fmt.Errorf("unsupported OS for Sync ssh_config: %s", l.goos))
	}

	return filepath.Clean(filepath.Join(parts...)), nil
}
