/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Organization struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Slug string `json:"slug,omitempty"`
}
