/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RoleAttachmentJson struct {
	Object string `json:"object,omitempty"`
	Role *RoleJson `json:"role,omitempty"`
	Subject string `json:"subject,omitempty"`
}
