/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
	BaseWorkspaceRepo string `json:"baseWorkspaceRepo,omitempty"`
	Email string `json:"email,omitempty"`
	ExternalAuthId string `json:"externalAuthId,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	PublicKey string `json:"publicKey,omitempty"`
	RoleAttachments []RoleAttachmentJson `json:"roleAttachments,omitempty"`
	Username string `json:"username,omitempty"`
	WorkspacePassword string `json:"workspacePassword,omitempty"`
}
