/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModifyWorkspaceRequest struct {
	IsStoppable bool `json:"isStoppable,omitempty"`
	Name string `json:"name,omitempty"`
	WorkspaceClassId string `json:"workspaceClassId,omitempty"`
}
