/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModifyUserRequest struct {
	BaseWorkspaceRepo string `json:"baseWorkspaceRepo,omitempty"`
	Email string `json:"email"`
	Name string `json:"name"`
	Username string `json:"username"`
}
