/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Workspace struct {
	CreatedAt string `json:"createdAt,omitempty"`
	CreatedByUserId string `json:"createdByUserId,omitempty"`
	Dns string `json:"dns,omitempty"`
	GitRepo string `json:"gitRepo,omitempty"`
	HealthStatus string `json:"healthStatus,omitempty"`
	Id string `json:"id,omitempty"`
	IsStoppable bool `json:"isStoppable,omitempty"`
	LastOnlineAt string `json:"lastOnlineAt,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizationId string `json:"organizationId,omitempty"`
	Password string `json:"password,omitempty"`
	Status string `json:"status,omitempty"`
	StatusMessage string `json:"statusMessage,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	Version string `json:"version,omitempty"`
	WorkspaceClassId string `json:"workspaceClassId,omitempty"`
	WorkspaceGroupId string `json:"workspaceGroupId,omitempty"`
	WorkspaceTemplate *WorkspaceTemplate `json:"workspaceTemplate,omitempty"`
}
