/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ErrorResponse struct {
	Errors []ModelError `json:"errors,omitempty"`
}
