/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateWorkspaceRequest struct {
	GitRepo string `json:"gitRepo,omitempty"`
	IsStoppable bool `json:"isStoppable,omitempty"`
	Name string `json:"name"`
	Version string `json:"version,omitempty"`
	WorkspaceClassId string `json:"workspaceClassId"`
	WorkspaceGroupId string `json:"workspaceGroupId"`
	WorkspaceTemplateId string `json:"workspaceTemplateId"`
}
