/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RoleJson struct {
	Actions []string `json:"actions,omitempty"`
	Id string `json:"id,omitempty"`
}
