/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {
	Actual string `json:"actual,omitempty"`
	Condition string `json:"condition,omitempty"`
	Field string `json:"field,omitempty"`
	Message string `json:"message,omitempty"`
	Type_ string `json:"type,omitempty"`
}
