/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkspaceRoleAttachmentRequest struct {
	Role string `json:"role"`
	Subject string `json:"subject"`
}
