/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkspaceUserJson struct {
	Role *RoleJson `json:"role,omitempty"`
	User *User `json:"user,omitempty"`
}
