/*
 * Brev API
 *
 * Brev REST API.
 *
 * API version: 0.1.0
 * Contact: support@brev.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkspaceGroup struct {
	BaseDns string `json:"baseDns,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Platform string `json:"platform,omitempty"`
	PlatformId string `json:"platformId,omitempty"`
	PlatformRegion string `json:"platformRegion,omitempty"`
	Status string `json:"status,omitempty"`
	Workspaces []Workspace `json:"workspaces,omitempty"`
}
