// Package mintcert implements the `brev mint-cert` command, which mints a
// short-lived SSH certificate for an environment and writes it (with its
// backing ephemeral keypair) to disk. It is invoked by the ssh config's
// Match exec hook, generated by `brev refresh`.
package mintcert

import (
	"context"
	"fmt"
	"os"
	"time"

	devplanev1 "buf.build/gen/go/brevdev/devplane/protocolbuffers/go/devplaneapi/v1"
	"connectrpc.com/connect"
	"github.com/brevdev/brev-cli/pkg/cmd/util"
	"github.com/spf13/afero"
	"github.com/spf13/cobra"

	"github.com/brevdev/brev-cli/pkg/cmd/register"
	"github.com/brevdev/brev-cli/pkg/config"
	breverrors "github.com/brevdev/brev-cli/pkg/errors"
	"github.com/brevdev/brev-cli/pkg/externalnode"
	"github.com/brevdev/brev-cli/pkg/sshcert"
)

const timeout = 15 * time.Second

type Store interface {
	util.GetWorkspaceByNameOrIDErrStore
	GetAccessToken() (string, error)
}

type CertIssuer interface {
	Issue(ctx context.Context, req certIssueRequest) (string, error)
}

type certIssueRequest struct {
	EnvironmentID string
	PortID        string
	LinuxUser     string
	PublicKey     string
}

type environmentCertClient interface {
	IssueEnvironmentSSHCertificate(ctx context.Context, req *connect.Request[devplanev1.IssueEnvironmentSSHCertificateRequest]) (*connect.Response[devplanev1.IssueEnvironmentSSHCertificateResponse], error)
}

type rpcCertIssuer struct {
	client environmentCertClient
}

func (r rpcCertIssuer) Issue(ctx context.Context, req certIssueRequest) (string, error) {
	res, err := r.client.IssueEnvironmentSSHCertificate(ctx, connect.NewRequest(&devplanev1.IssueEnvironmentSSHCertificateRequest{
		EnvironmentId: req.EnvironmentID,
		LinuxUser:     req.LinuxUser,
		PortId:        req.PortID,
		PublicKey:     req.PublicKey,
	}))
	if err != nil {
		return "", breverrors.WrapAndTrace(err)
	}
	return res.Msg.GetCertificate(), nil
}

func NewCmdMintCert(store Store) *cobra.Command {
	var (
		env    string
		port   string
		user   string
		outKey string
	)
	cmd := &cobra.Command{
		Use:    "mint-cert",
		Short:  "Mint a short-lived SSH certificate for an environment",
		Args:   cobra.NoArgs,
		Hidden: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runMintCert(store, mintCertRequest{
				NameOrID:  env,
				PortID:    port,
				LinuxUser: user,
				OutKey:    outKey,
			})
		},
	}
	cmd.Flags().StringVar(&env, "env", "", "name or ID to mint a certificate for")
	cmd.Flags().StringVar(&port, "port", "", "network-member port ID for the SSH access")
	cmd.Flags().StringVar(&user, "linux-user", "", "Linux user for the certificate principal")
	cmd.Flags().StringVar(&outKey, "out-key", "", "private-key path (certificate goes to <path>-cert.pub)")
	_ = cmd.MarkFlagRequired("env")
	_ = cmd.MarkFlagRequired("port")
	_ = cmd.MarkFlagRequired("linux-user")
	_ = cmd.MarkFlagRequired("out-key")
	return cmd
}

type mintCertRequest struct {
	NameOrID  string
	PortID    string
	LinuxUser string
	OutKey    string
}

func runMintCert(store Store, req mintCertRequest) error {
	return runMintCertWith(store, afero.NewOsFs(), newCertIssuer(store, config.GlobalConfig.GetBrevPublicAPIURL()), req)
}

func runMintCertWith(store Store, fs afero.Fs, issuer CertIssuer, req mintCertRequest) error {
	token, err := store.GetAccessToken()
	if err != nil || token == "" {
		_, _ = fmt.Fprintln(os.Stderr, "brev: not logged in. Run `brev login` and retry.")
		if err != nil {
			return breverrors.WrapAndTrace(err)
		}
		return fmt.Errorf("not logged in")
	}
	target, err := util.ResolveWorkspaceOrNode(store, req.NameOrID)
	if err != nil {
		return breverrors.WrapAndTrace(err)
	}
	var targetId string
	if target.Workspace != nil {
		targetId = target.Workspace.ID
	}
	if target.Node != nil {
		// TODO uptake for external node
		return breverrors.New("registered compute not yet supported for SSH Certs")
	}

	certPath := req.OutKey + "-cert.pub"

	if ok, err := sshcert.HasValidCertAuth(fs, req.OutKey, certPath, time.Now(), sshcert.DefaultRenewalMargin); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "brev: failed to check cached cert: %v\n", err)
		return breverrors.WrapAndTrace(err)
	} else if ok {
		return nil
	}

	privKeyPEM, pubKeyOpenSSH, err := sshcert.GenerateKeyPair()
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "brev: failed to generate keypair: %v\n", err)
		return breverrors.WrapAndTrace(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	cert, err := issuer.Issue(ctx, certIssueRequest{
		EnvironmentID: targetId,
		PortID:        req.PortID,
		LinuxUser:     req.LinuxUser,
		PublicKey:     pubKeyOpenSSH,
	})
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "brev: could not issue ssh certificate: %v\n", err)
		return breverrors.WrapAndTrace(err)
	}
	if err := sshcert.WriteFiles(fs, req.OutKey, certPath, privKeyPEM, cert); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "brev: failed to write cert files: %v\n", err)
		return breverrors.WrapAndTrace(err)
	}
	return nil
}

func newCertIssuer(provider externalnode.TokenProvider, baseURL string) CertIssuer {
	return rpcCertIssuer{client: register.NewEnvironmentServiceClient(provider, baseURL)}
}
